version: '3'

services:

  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mariadb
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress

  wp:
    image: wordpress:cli
    volumes:
      - ./:/var/www/html
